In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [25]:
import numpy as np
import matplotlib.pyplot as plt

un_o_matrix = np.mat([[1, 2, 3, 4], [2, 5, 7, 2], [2, 4, 3, 5], [1, 4, 5, 6]])
row_len, column_len = un_o_matrix.shape
x1, x2, x3, x4 = un_o_matrix[0, :], un_o_matrix[1, :], un_o_matrix[2, :], un_o_matrix[3, :]
x1_new = x1
x2_new = x2 - (np.dot(x2, x1_new.T) / np.dot(x1_new, x1_new.T))[0, 0] * x1_new
x3_new = x3 - (np.dot(x3, x1_new.T) / np.dot(x1_new, x1_new.T))[0, 0] * x1_new - (np.dot(
    x3, x2_new.T) / np.dot(x2_new, x2_new.T))[0, 0] * x2_new
x4_new = x4 - (np.dot(x4, x1_new.T) / np.dot(x1_new, x1_new.T))[0, 0] * x1_new - (np.dot(
    x4, x2_new.T) / np.dot(x2_new, x2_new.T))[0, 0] * x2_new - (
                 np.dot(x4, x3_new.T) / np.dot(x3_new, x3_new.T))[0, 0] * x3_new
o_matrix = np.vstack([x1_new, x2_new, x3_new, x4_new])
print(o_matrix)

# normalization
x1_new = x1_new/np.linalg.norm(x1_new)
x2_new = x2_new/np.linalg.norm(x2_new)
x3_new = x3_new/np.linalg.norm(x3_new)
x4_new = x4_new/np.linalg.norm(x4_new)
o_matrix = np.vstack([x1_new, x2_new, x3_new, x4_new])
print('Orthogonal : {}'.format(o_matrix))

sum_x = np.log(np.linalg.norm(o_matrix[0, :]))

[[ 1.          2.          3.          4.        ]
 [ 0.63333333  2.26666667  2.9        -3.46666667]
 [ 0.65853659  1.25160462 -1.08985879  0.02695764]
 [-0.76086957  0.35507246 -0.05072464  0.05072464]]
Orthogonal : [[ 0.18257419  0.36514837  0.54772256  0.73029674]
 [ 0.12428658  0.44481514  0.56910172 -0.6803055 ]
 [ 0.36878465  0.70090651 -0.61032782  0.01509645]
 [-0.9028939   0.42135049 -0.06019293  0.06019293]]


In [31]:
delta_x = np.mat([[1, 2, 2, 2], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
print(delta_x[0, :])
print(np.linalg.norm(delta_x[0, :]))
x1 = np.log(np.linalg.norm(delta_x[0, :]))
print(x1)

[[1 2 2 2]]
3.605551275463989
1.2824746787307684
